# Generated by Django 3.2.15 on 2022-10-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20221023_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='description',
            field=models.TextField(default='', verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='дата публикации'),
        ),
    ]
