# Generated by Django 3.2.15 on 2022-10-23 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_auto_20221023_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app_news.newstype'),
        ),
    ]
