# Generated by Django 4.0.4 on 2022-05-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0007_advertisementtype_advertisement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
