# Generated by Django 2.2 on 2022-05-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0010_auto_20220516_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementstatus',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='advertisementtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='advertisementstatus',
            table='advertisement_status',
        ),
        migrations.AlterModelTable(
            name='advertisementtype',
            table='advertisement_type',
        ),
    ]
