# Generated by Django 2.2 on 2022-06-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0015_auto_20220607_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(choices=[('a', False), ('i', True)], default=False),
        ),
    ]
