# Generated by Django 2.2 on 2022-06-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0016_auto_20220623_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(choices=[('a', True), ('i', False)], default=False),
        ),
    ]
