# Generated by Django 2.2 on 2022-06-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0004_auto_20220622_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('r', 'Review'), ('p', 'Published')], default='', max_length=1),
        ),
    ]
