# Generated by Django 2.2 on 2022-09-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_remove_blog_files'),
        ('app_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_blog.Blog'),
            preserve_default=False,
        ),
    ]
