# Generated by Django 3.2.15 on 2022-10-28 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housing',
            options={'verbose_name': 'жилье', 'verbose_name_plural': 'жилище'},
        ),
        migrations.AlterModelOptions(
            name='quantityofrooms',
            options={'verbose_name': 'количество комнат', 'verbose_name_plural': 'количество комнат'},
        ),
        migrations.AlterModelOptions(
            name='typeofhouse',
            options={'verbose_name': 'тип помещения', 'verbose_name_plural': 'типы помещений'},
        ),
        migrations.AlterField(
            model_name='housing',
            name='quantity_of_rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_housing.quantityofrooms'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='type_of_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_housing.typeofhouse'),
        ),
    ]
