# Generated by Django 3.2.15 on 2022-10-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_housing', '0002_auto_20221028_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='дата публикации'),
        ),
    ]
