# Generated by Django 2.2 on 2022-10-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='лайки'),
        ),
    ]
