# Generated by Django 2.2 on 2022-10-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Новичок', max_length=100, verbose_name='статус')),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
