# Generated by Django 2.2 on 2022-10-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_userprofile2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile2',
        ),
    ]
