# Generated by Django 2.2 on 2022-06-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0002_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='waiter',
        ),
    ]
