# Generated by Django 2.2 on 2022-06-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0003_remove_restaurant_waiter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.AddField(
            model_name='test',
            name='waiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_library.Waiter'),
            preserve_default=False,
        ),
    ]
