# Generated by Django 2.2 on 2022-06-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0004_auto_20220622_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test',
        ),
    ]
