# Generated by Django 2.2 on 2022-06-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0007_auto_20220622_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='test',
        ),
    ]
