# Generated by Django 2.2 on 2022-06-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0008_remove_restaurant_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiter',
            old_name='waiter',
            new_name='Restaurant',
        ),
    ]
