# Generated by Django 2.2 on 2022-06-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0009_auto_20220622_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiter',
            old_name='Restaurant',
            new_name='restaurant',
        ),
    ]
