# Generated by Django 2.2 on 2022-09-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='files',
        ),
    ]
