# Generated by Django 3.2.15 on 2022-10-07 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_electronic_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='Author',
        ),
    ]
